const CATS = {
  alist: "International — A-List",
  genre: "International — Genre & Regional",
  indian: "Indian",
  ai: "AI-Generated Film"
};

const FESTIVALS = [
// ---------------- INTERNATIONAL A-LIST ----------------
{ id:"cannes", cat:"alist", name:"Cannes Film Festival", loc:"Cannes, France",
  dates:"May 12–23, 2026 (79th ed.) · 80th ed. May 11–22, 2027",
  deadline:"Official Selection shorts Mar 2 · features Mar 13 · Directors' Fortnight Mar 13–14 · Critics' Week (date TBC on site)",
  deadlineISO:"2026-03-14",
  concept:"The world's most prestigious festival. Official Selection favors world premieres of auteur/arthouse features; Directors' Fortnight and Critics' Week are independently curated parallel sections built around discovery and first/second-time filmmakers.",
  fee:"Official Selection: free online registration (DVD/Blu-ray delivery €50, DCP €300). Directors' Fortnight: free (features) / €55 (shorts). Critics' Week: €35 (shorts).",
  formats:"Feature (In Competition, Un Certain Regard, Out of Competition), Short (Official Competition, Cinéfondation/student)",
  docs:"Online form via festival 'My Account' portal; screener upload or link (max 8GB) or DCP; film must be unreleased; French-language films need English-subtitled DCP; post-selection requires a press kit and royalty-free clip.",
  platform:"Own portal (festival-cannes.com); Quinzaine and Semaine run separate own portals",
  url:"https://www.festival-cannes.com/en/take-part/submit-a-film/" },

{ id:"berlinale", cat:"alist", name:"Berlin International Film Festival (Berlinale)", loc:"Berlin, Germany",
  dates:"76th ed. Feb 12–22, 2026 · 77th ed. Feb 10–21, 2027",
  deadline:"2027-edition deadlines not yet published — expected ~Oct/Nov 2026 based on pattern",
  deadlineISO:null, statusOverride:"tba",
  concept:"Major competitive A-list festival. Sections span Competition, Berlinale Special, Perspectives, Panorama, Generation (youth), and Berlinale Shorts, plus the independently curated Forum/Forum Expanded. Several non-Competition sections require a European premiere.",
  fee:"€175 flat (feature) · €75 flat (short) — regardless of how many sections you apply to",
  formats:"Feature narrative/doc, short, youth/family (Generation), experimental (Forum), episodic (Berlinale Series)",
  docs:"Online registration, then a selection screener upload via the Berlinale Media Service; DCP or ProRes on invitation.",
  platform:"Own portal (berlinale.de)",
  url:"https://www.berlinale.de/en/film-entry/" },

{ id:"venice", cat:"alist", name:"Venice Film Festival (Biennale Cinema)", loc:"Venice, Italy",
  dates:"83rd ed. Sept 2–12, 2026 · 84th ed. dates not yet announced",
  deadline:"Immersive/VR May 7 · Classics (free) May 4 · Shorts May 28 (late tier from Apr 30, higher fee) · Features Jun 4 23:59 (late tier from May 15, fee rises to €250) — all 2026",
  deadlineISO:"2026-06-04",
  concept:"The world's oldest film festival. Strict world-premiere-only policy for features and shorts across the main competition, Orizzonti, Venice Spotlight, and Venice Classics. Independent parallel sections: Critics' Week (first films only) and Giornate degli Autori.",
  fee:"Feature €200 → €250 (late) · Short €80 → €100 (late) · Immersive €200 → €250 · Restored classics free",
  formats:"Narrative feature, documentary feature, short, immersive/VR, restored classics",
  docs:"Online pre-selection entry form (opens ~Feb 9); screener link/upload; world-premiere status is mandatory for competitive sections.",
  platform:"Own portal (labiennale.org)",
  url:"https://www.labiennale.org/en/cinema/2026/submitting-film" },

{ id:"sundance", cat:"alist", name:"Sundance Film Festival", loc:"Boulder, Colorado, USA (relocating from Park City for 2027)",
  dates:"2027 ed. Jan 21–31, 2027",
  deadline:"Shorts early $55 (Jul 13) · Episodic early $55 (Jul 24) · Features early $80 (Jul 27) · Shorts window closes Aug 31 · Features window closes Sep 21 — mid/late-tier fees unconfirmed",
  deadlineISO:"2026-09-21",
  concept:"The premier U.S. independent film showcase, with strong tracks for U.S. and international narrative and documentary features plus dedicated short/episodic categories. Projects must be completed in 2026; no public exhibition before Feb 1, 2027.",
  fee:"Early tiers: Short/Episodic $55, Feature $80. Regular/late tiers exist but exact fees are unconfirmed publicly — verify on FilmFreeway.",
  formats:"Narrative feature, documentary feature, short (U.S. &amp; international), episodic/series",
  docs:"Submission via FilmFreeway; screener, synopsis, and standard project info per the published Submissions FAQ/Rules.",
  platform:"FilmFreeway",
  url:"https://www.sundance.org/festivals/sundance-film-festival/submit/" },

{ id:"tiff", cat:"alist", name:"Toronto International Film Festival (TIFF)", loc:"Toronto, Canada",
  dates:"51st ed. Sept 10–20, 2026 · 2027 dates not yet announced",
  deadline:"Single standard deadline: May 8, 2026, 11:59pm ET",
  deadlineISO:"2026-05-08",
  concept:"Major North American launchpad with a Canadian-content mandate alongside international premieres. Sections include Galas &amp; Special Presentations, Platform, Discovery (1st/2nd features), Wavelengths (experimental), TIFF Docs, Short Cuts, and Midnight Madness (genre).",
  fee:"CAD — Canadian Feature $155 ($131.75 Industry) · Canadian Short $75 ($63.75) · International Feature $155 ($131.75) · International Short $95 ($80.75) · Primetime (episodic) $100 ($85)",
  formats:"Narrative/doc feature, short, episodic — split into Canadian vs. International fee tiers",
  docs:"FilmFreeway only; screener required (listing stays 'Incomplete' until received) — no physical DVD/Blu-ray accepted.",
  platform:"FilmFreeway",
  url:"https://tiff.net/submissions" },

{ id:"busan", cat:"alist", name:"Busan International Film Festival (BIFF)", loc:"Busan, South Korea",
  dates:"31st ed. Oct 6–15, 2026 · 2027 dates not yet announced",
  deadline:"Shorts Jun 2, 2026, 18:00 KST · Features Jul 8, 2026, 18:00 KST",
  deadlineISO:"2026-07-08",
  concept:"Asia's leading A-list festival with a strong regional focus on Asian cinema. New Currents competition is reserved for first/second features by emerging Asian directors; priority given to World or International Premieres.",
  fee:"Free — no submission fee",
  formats:"Feature narrative, documentary, animation, short (Asian focus for competition sections)",
  docs:"Direct submission via biff.kr; official submission triggers a screener-upload email; re-submitting a previously submitted film generally isn't allowed.",
  platform:"Own portal (biff.kr)",
  url:"https://www.biff.kr/eng/",
  note:"Distinct from the Busan International Short Film Festival (BISFF, April) — a separate, fee-charging event, not a BIFF section." },

{ id:"locarno", cat:"alist", name:"Locarno Film Festival", loc:"Locarno, Switzerland",
  dates:"79th ed. Aug 5–15, 2026 · possible July shift for the 80th (2027) anniversary edition, unconfirmed",
  deadline:"Early Feb 19 · Regular Apr 9 · Late Apr 23, 2026 (14:00 CET)",
  deadlineISO:"2026-04-23",
  concept:"Major arthouse/discovery festival known for outdoor Piazza Grande screenings (8,000-seat public venue) and the Pardi di Domani short-film sections for first-time and established directors.",
  fee:"Short CHF 35–75 (tiered by deadline) · Feature CHF 100–200 (tiered) — exact per-tier breakdown unconfirmed",
  formats:"Feature narrative/doc (Concorso Internazionale, Cineasti del Presente, Piazza Grande), short/medium-length (Pardi di Domani — 3 sub-competitions)",
  docs:"Online submission through the festival platform; standard project/screener info — full itemized checklist unconfirmed, verify at locarnofestival.ch.",
  platform:"Own portal (locarnofestival.ch)",
  url:"https://www.locarnofestival.ch/Film-Submission.html" },

{ id:"sansebastian", cat:"alist", name:"San Sebastián International Film Festival", loc:"San Sebastián, Spain",
  dates:"74th ed. Sept 18–26, 2026 · 2027 dates not yet announced",
  deadline:"Single deadline: June 16, 2026",
  deadlineISO:"2026-06-16",
  concept:"Spain's top A-list festival with strong Spanish/Latin American ties (Horizontes Latinos), alongside Official Selection, New Directors, Zabaltegi-Tabakalera, and Zinemira (Basque cinema).",
  fee:"Short/medium (31–59 min) €70 incl. VAT · Feature (60+ min) €100–110 incl. VAT (sources vary — confirm exact figure) · DCP delivery surcharge €210",
  formats:"Narrative/doc feature, short/medium-length, Horizontes Latinos, New Directors, Zinemira",
  docs:"Online entry form; synopsis, technical/artistic credits, bio-filmographies, director photos and stills; film must be produced within the 12 months prior to the festival.",
  platform:"Own portal — not FilmFreeway/Festhome for the main festival",
  url:"https://www.sansebastianfestival.com/2026/film_registration/1/4908/in" },

// ---------------- INTERNATIONAL GENRE & REGIONAL ----------------
{ id:"iffr", cat:"genre", name:"International Film Festival Rotterdam (IFFR)", loc:"Rotterdam, Netherlands",
  dates:"55th ed. Jan 29–Feb 8, 2026 · 56th ed. (2027) dates not yet confirmed",
  deadline:"For the 2027 festival — Early Jun 15, 2026 (€65/€40) · Standard Aug 31, 2026 (€85/€55) · Late Sep 15, 2026 (€110/€70) — feature/short",
  deadlineISO:"2026-09-15",
  concept:"Adventurous, arthouse-leaning festival built around discovering new and independent filmmaking talent. Tiger Competition is reserved for directors' 1st–3rd feature and requires a world premiere; Bright Future covers debuts, Harbour contemporary cinema.",
  fee:"Feature €65 (early) → €110 (late) · Short €40 (early) → €70 (late)",
  formats:"Feature (Tiger Competition, Big Screen Competition, Bright Future, Harbour), short/mid-length (Tiger Short Competition)",
  docs:"Online entry via a personal IFFR account; streaming screener link with a password valid through the festival; director's statement; film completed after Jan 1, 2026.",
  platform:"Own portal (iffr.com)",
  url:"https://iffr.com/en/iffr-pro-submissions/film-entry" },

{ id:"sxsw", cat:"genre", name:"SXSW Film &amp; TV Festival", loc:"Austin, Texas, USA",
  dates:"2027 ed. Mar 15–21, 2027",
  deadline:"Submissions open Jul 28, 2026 · First deadline Aug 25 · Second Sep 15 · Final Oct 1, 2026 · Notifications Feb 9, 2027",
  deadlineISO:"2026-10-01",
  concept:"A convergence of film, tech, and culture — not strictly premiere-exclusive, but competition sections favor North American/world premieres. Broad mix of indie narrative, doc, genre (Midnighters), and episodic work.",
  fee:"Indicative only (last confirmed cycle, verify for 2027): Feature ~$70→$120 across tiers · Short/TV ~$50→$85 across tiers",
  formats:"Narrative/doc feature (&gt;40 min), short (≤40 min, incl. Texas Shorts), episodic/TV pilots, music videos (&lt;10 min), XR",
  docs:"Online application via the SXSW Cart portal; screener link, synopsis, director bio.",
  platform:"Own portal (cart.sxsw.com)",
  url:"https://sxsw.com/apply/film-submissions/" },

{ id:"tribeca", cat:"genre", name:"Tribeca Festival", loc:"New York City, USA",
  dates:"2026 ed. (25th anniversary) Jun 3–14, 2026 · 2027 dates not yet announced",
  deadline:"2026-cycle tiers (all closed): Features/TV through Dec 17, 2025 · Shorts/NOW through Feb 4–5, 2026 · Games/Podcasts through Feb 11, 2026",
  deadlineISO:"2026-02-04",
  concept:"NYC-based broad independent showcase spanning narrative, documentary, TV/episodic, games, and immersive/audio storytelling, with a strong preference for world premieres.",
  fee:"Reference pricing (reconfirm each cycle): Feature $65→$110 across tiers · Short $50→$75 across tiers (a $35 promo rate is sometimes available)",
  formats:"Narrative/doc feature &amp; short, Tribeca TV, Games, Audio Storytelling (podcasts), NOW (nonfiction), Immersive",
  docs:"Password-protected streaming URL active through the festival; short &amp; long synopsis; director's statement (~200–400 words); credits; press kit; stills; poster.",
  platform:"FilmFreeway or Tribeca's own Eventival-based portal",
  url:"https://tribecafilm.com/festival/submissions",
  note:"2027-cycle deadlines not yet announced — expect an opening around September 2026 based on prior years." },

{ id:"clermont", cat:"genre", name:"Clermont-Ferrand International Short Film Festival", loc:"Clermont-Ferrand, France",
  dates:"48th ed. Jan 30–Feb 7, 2026 · 49th ed. Jan 29–Feb 6, 2027",
  deadline:"Early Jul 9, 2026 (films completed Oct–Dec 2025) · Regular/Final Sep 24, 2026 (films from 2026)",
  deadlineISO:"2026-09-24",
  concept:"The world's largest short-film festival and market. Three parallel competitions — International (non-French, ≤40 min), National (French-language, ≤59 min), and Lab (experimental) — feed automatically into the Short Film Market. FIAPF-accredited and Oscar/BAFTA/EFA/César-qualifying.",
  fee:"Flat €13 (plus one ShortFilmDepot 'stamp') — no early-bird discount; 50% off for schools/distributors submitting multiple directors' films",
  formats:"Fiction, animation, documentary, experimental shorts across International/National/Lab",
  docs:"Submit via Shortfilmdepot.com; if selected, DCP delivery (no KDM encryption) via FTP; non-embedded French subtitles requested for non-French films.",
  platform:"Shortfilmdepot.com (exclusive)",
  url:"https://www.lecourt-clermont.org/en/pros/submit-a-film/" },

{ id:"psiff", cat:"genre", name:"Palm Springs International Film Festival (PSIFF)", loc:"Palm Springs, California, USA",
  dates:"38th ed. Jan 7–18, 2027",
  deadline:"Submissions open now; Early Bird fee-waiver ran Apr 6–Jun 6, 2026. Full tiered schedule (regular/late/final dates and fees) not publicly confirmed — verify on FilmFreeway.",
  deadlineISO:null, statusOverride:"tba",
  concept:"A 'best-of' pre-Oscar showcase — the largest platform in the U.S. for countries' official Oscar International Feature submissions. Typically programs films that already premiered at Cannes, Venice, or TIFF rather than seeking world premieres. Does not accept short films (see the separate ShortFest).",
  fee:"Exact dollar figures unconfirmed for the 2027 cycle — check FilmFreeway directly.",
  formats:"Narrative &amp; documentary feature only (≥70 minutes) — no shorts",
  docs:"Digital screener (Vimeo preferred); standard FilmFreeway submission fields.",
  platform:"FilmFreeway",
  url:"https://filmfreeway.com/PalmSpringsInternationalFilmFestival",
  note:"Separate sister event, Palm Springs ShortFest (shorts only), typically runs in June — 2027 dates not yet published." },

{ id:"bfilff", cat:"genre", name:"BFI London Film Festival (LFF)", loc:"London, UK",
  dates:"70th ed. Oct 7–18, 2026",
  deadline:"Submissions for the 70th edition already closed. Reference tiers from a recent cycle: Early Bird late March · Regular late March–May · Late through late May — verify current dates directly with BFI.",
  deadlineISO:"2026-05-24",
  concept:"Primarily a curated 'festival of festivals' showcasing UK/European premieres of films that already bowed at Cannes, Venice, or TIFF. Open public submissions apply specifically to UK &amp; Ireland-made shorts, mid-length, and feature films — the main international programme is invitation-only.",
  fee:"Reference (2024 cycle, reconfirm current): Short £18→£40 across tiers · Feature £35→£70–75 across tiers",
  formats:"UK &amp; Ireland short (≤25 min), mid-length (26–50 min), feature (&gt;50 min) — open-submission track only",
  docs:"BFI's own portal or FilmFreeway; screener, synopsis, credits.",
  platform:"BFI own portal + FilmFreeway",
  url:"https://www.bfi.org.uk/explore-our-festivals/70th-bfi-london-film-festival-submissions",
  note:"Next submission window expected roughly Q1 2027 for the 71st edition." },

{ id:"sitges", cat:"genre", name:"Sitges — International Fantastic Film Festival of Catalonia", loc:"Sitges, Spain",
  dates:"59th ed. Oct 8–18, 2026",
  deadline:"Window: Feb 23–Jul 16, 2026, 12:00 CET · Early Bird through Jun 18 · Final Jun 19–Jul 16",
  deadlineISO:"2026-07-16",
  concept:"The world's leading specialized fantastic-genre festival — horror, sci-fi, fantasy — one of the 'big three' genre festivals alongside Fantasia and Fantastic Fest.",
  fee:"Feature: Early €80 / Final €90 · Short: Early €60 / Final €70 (Official Fantàstic, Brigadoon, Sitges Family categories)",
  formats:"Official Fantàstic (feature &amp; short), Anima't (animation), Brigadoon (midnight/cult), Midnight X-Treme, Noves Visions, Òrbita, Panorama, Sitges Family — max short runtime 30 min, Oscar-qualifying eligible",
  docs:"Standard submission (synopsis, credits, screener link). FanPitch industry strand additionally needs a PDF script + info pack and a 3-minute English-language pitch video.",
  platform:"FilmFreeway and Festhome",
  url:"https://sitgesfilmfestival.com/en/film-submission/faqs" },

{ id:"annecy", cat:"genre", name:"Annecy International Animation Film Festival", loc:"Annecy, France",
  dates:"2026 ed. Jun 21–27, 2026 (shifted later due to a G7 conflict) · 2027 ed. Jun 13–19, 2027",
  deadline:"2026-cycle deadlines (closed): Short/Graduation/TV Feb 15, 2026 · Feature Mar 15, 2026. 2027 submissions expected to open around October 2026 — exact dates not yet published.",
  deadlineISO:"2026-03-15",
  concept:"The world's premier animation-only festival and market — the 'Cannes of animation' — spanning all animation genres and formats.",
  fee:"Short €30 · TV/commissioned €50 · Feature €100 · Graduation/student €10",
  formats:"Short, Feature (Official Selection/Contrechamp/Annecy Presents), Graduation/Student, TV &amp; Commissioned, Immersive (VR/XR)",
  docs:"Own registration portal; password-protected web link or direct upload (5GB max); 1–3 HD images; filmography (max 3 titles); synopsis ≤250 characters, FR or EN.",
  platform:"Own portal (annecyfestival.com)",
  url:"https://www.annecyfestival.com/en/take-part/submit-film" },

// ---------------- INDIAN ----------------
{ id:"iffi", cat:"indian", name:"International Film Festival of India (IFFI)", loc:"Goa, India",
  dates:"57th ed. Nov 20–28, 2026",
  deadline:"Indian Panorama entries Aug 10, 2026, 6:00pm IST · International Competition preview material Aug 31, 2026 · CBFC certificate due by Nov 20, 2026",
  deadlineISO:"2026-08-31",
  concept:"India's flagship international festival — world cinema competition, retrospectives, the Indian Panorama showcase of the year's best Indian features/non-features, masterclasses, and the ICFT-UNESCO Gandhi Medal.",
  fee:"International Competition: free (per FilmFreeway listing). Indian Panorama fee unconfirmed — likely free/nominal as a government-run selection.",
  formats:"International Competition (feature), Indian Panorama Feature/Non-Feature/Best Debut Director, curated sections",
  docs:"Online screener/preview link, synopsis, director bio, stills, CBFC certificate (Indian films).",
  platform:"FilmFreeway (international/competition entries); Indian Panorama runs through NFDC's own portal — verify directly",
  url:"https://iffigoa.org/" },

{ id:"mami", cat:"indian", name:"Jio MAMI Mumbai Film Festival", loc:"Mumbai, India",
  dates:"No confirmed dates since the 2025 hiatus announcement",
  deadline:"—",
  deadlineISO:null, statusOverride:"hiatus",
  concept:"Was Mumbai's flagship independent festival. Publicly cancelled its 2025 edition (announced by director Shivendra Singh Dungarpur) for a full organizational, leadership, and funding overhaul, following earlier sponsor exits (American Express, Reliance). No confirmed 2026 dates or reopened submission process as of this research.",
  fee:"—", formats:"—",
  docs:"Not applicable while the full festival is inactive.",
  platform:"—",
  url:"https://mumbaifilmfestival.com/",
  note:"Only currently-live activity: 'MAMI Select', a small year-round shorts programme for 4 emerging filmmakers (Hindi/Marathi/Malayalam/Bengali, 20–40 min) — its deadline (Jan 9, 2026) has already passed and it is not equivalent to the full festival." },

{ id:"iffk", cat:"indian", name:"International Film Festival of Kerala (IFFK)", loc:"Thiruvananthapuram, India",
  dates:"30th ed. Dec 12–19, 2025 (past) · 31st ed. Dec 11–18, 2026",
  deadline:"2026-edition submission dates not yet published — the 30th-ed. pattern (window Aug 12–Sep 14) suggests a similar Aug–Sep 2026 window",
  deadlineISO:null, statusOverride:"tba",
  concept:"Government-run (Kerala State Chalachitra Academy), one of India's most respected arthouse/world-cinema festivals, with a strong Malayalam and regional-language focus alongside a competitive international section.",
  fee:"No confirmed filmmaker submission fee (state-run festivals in Kerala are typically free to enter). Delegate/attendee registration is ₹1,000 general / ₹500 student — a separate attendee fee, not a submission fee.",
  formats:"International Competition (feature, 70+ min, India premiere required), Malayalam Cinema Today, World Cinema, retrospectives",
  docs:"Online screener via Eventival; synopsis and credits. Eventival is strict that only online screeners count as preview material.",
  platform:"Eventival (vp.eventival.com/idsffk)",
  url:"https://iffk.in/",
  note:"Sister event: the International Documentary &amp; Short Film Festival of Kerala (IDSFFK) runs separately — see below, don't conflate the two." },

{ id:"idsffk", cat:"indian", name:"International Documentary &amp; Short Film Festival of Kerala (IDSFFK)", loc:"Kerala, India",
  dates:"Runs alongside the Kerala Chalachitra Academy's annual calendar",
  deadline:"2026 call for entries reported active; exact deadline unconfirmed",
  deadlineISO:null, statusOverride:"tba",
  concept:"IFFK's sister event for documentary and short films, run by the same Kerala State Chalachitra Academy.",
  fee:"₹1,000 (documentary/short, general) · ₹500 (student 'campus' films)",
  formats:"Documentary, short, student/campus films",
  docs:"Likely the same Eventival-based system as IFFK — verify directly before submitting.",
  platform:"Presumed Eventival (unconfirmed)",
  url:"https://iffk.in/" },

{ id:"diff", cat:"indian", name:"Dharamshala International Film Festival (DIFF)", loc:"Dharamshala, Himachal Pradesh, India",
  dates:"15th ed. Oct 29–Nov 1, 2026",
  deadline:"Regular deadline Aug 2, 2026 · a later/extended tier exists at a higher fee (exact date unconfirmed)",
  deadlineISO:"2026-08-02",
  concept:"An independent, non-competitive mountain-town festival showcasing indie fiction and documentary work from India and worldwide — more curatorial festival-community than industry market.",
  fee:"USD, via FilmFreeway — Short/Doc ≤25 min: Regular $30 (Gold $27) / Late $50 (Gold $45). Feature: Regular $60 (Gold $54). Overall range $20–75.",
  formats:"Shorts (&lt;25 min), mid-length (26–59 min), features (60+ min), fiction and documentary",
  docs:"4 film stills (TIFF/JPEG, min 10×4in @300dpi), director headshot, digital press notes PDF, digital poster, HD screener. Must be a Dharamshala premiere, not otherwise available online, completed after Jan 1 of the eligibility year; English subtitles required for non-English films.",
  platform:"FilmFreeway",
  url:"https://diff.co.in/" },

{ id:"biffes", cat:"indian", name:"Bengaluru International Film Festival (BIFFES)", loc:"Bengaluru, India",
  dates:"17th ed. Jan 29–Feb 6, 2026 (past) · 18th ed. dates not yet announced",
  deadline:"17th-ed. window ran Dec 6–31, 2025 with CBFC certificate due Jan 3, 2026. Next edition's dates not yet published.",
  deadlineISO:null, statusOverride:"tba",
  concept:"Karnataka's state-run, FIAPF-accredited flagship festival — a Kannada Cinema Competition alongside Indian and Asian Cinema Competitions and non-competitive World Cinema.",
  fee:"₹3,000 per film entry (Karnataka/Indian films in the Indian, Kannada, and Asian Cinema Competition sections). A notarized affidavit on ₹50–100 stamp paper is also required for Indian entries.",
  formats:"Kannada Cinema Competition (feature fiction, 70+ min), Indian Cinema (Chitrabharati) Competition, Asian Cinema Competition, Kannada Cinema of Popular Entertainment, World Cinema (non-competitive)",
  docs:"CBFC certificate dated within the eligibility window, notarized affidavit, standard submission package.",
  platform:"Own portal (biffes.org/submission)",
  url:"https://biffes.org/" },

{ id:"ciff", cat:"indian", name:"Chennai International Film Festival (CIFF)", loc:"Chennai, India",
  dates:"23rd ed. Dec 11–18, 2025 (past) · 24th ed. dates and call for entries not yet published",
  deadline:"Not yet published for the 24th edition. 23rd-ed. eligibility windows (for pattern reference): Tamil Features CBFC-certified Oct 2025–Oct 2026; World Cinema Competition completed after Nov 1, 2025; Indian Panorama after Oct 1, 2025.",
  deadlineISO:null, statusOverride:"tba",
  concept:"Tamil Nadu's premier film-culture festival — a strong Tamil-language feature focus alongside a World Cinema competition, run by the Indo Cine Appreciation Foundation with Tamil Nadu government/NFDC support.",
  fee:"Exact amount unconfirmed — a fee is confirmed to exist (non-refundable for wrong-category entries) but the figure wasn't surfaced in public sources.",
  formats:"Tamil Feature competition (70+ min, one Indian producer required), World Feature competition, Indian Panorama, World Cinema non-competition",
  docs:"Standard FilmFreeway package.",
  platform:"FilmFreeway only",
  url:"https://filmfreeway.com/chennaiintlfilmfest" },

{ id:"kiff", cat:"indian", name:"Kolkata International Film Festival (KIFF)", loc:"Kolkata, India",
  dates:"30th ed. Nov 6–13, 2025 (past) · 31st ed. Nov 6–13, 2026",
  deadline:"30th-ed. cutoff was Sep 25, 2025; 31st-ed. (2026) deadline not yet published — expect a similar Sep/Oct 2026 window",
  deadlineISO:null, statusOverride:"tba",
  concept:"West Bengal's state-run flagship festival, opened annually by the Chief Minister — a strong Bengali-cinema showcase plus an international competition, shorts, and documentary sections across 20+ venues.",
  fee:"Free — confirmed explicitly in official KIFF regulations, including for short/documentary sections.",
  formats:"Fiction features (60+ min), shorts (&lt;30 min), documentaries (&lt;60 min)",
  docs:"DCP-2K preferred for selected films (MOV/MP4/ProRes/DVD/Blu-ray accepted in limited cases), per instructions in the official invitation letter.",
  platform:"Own portal (kiff.in) — not FilmFreeway",
  url:"https://kiff.in/",
  note:"Several unrelated smaller 'Kolkata'-branded festivals exist on FilmFreeway (International Kolkata Short Film Festival, Ritu Rangam KIFF, etc.) — don't conflate them with the official state KIFF." },

{ id:"piff", cat:"indian", name:"Pune International Film Festival (PIFF)", loc:"Pune, India",
  dates:"25th ed. Jan 14–21, 2027",
  deadline:"Feature submissions close Oct 31, 2026",
  deadlineISO:"2026-10-31",
  concept:"Maharashtra-focused festival with a dedicated Marathi Competition (Sant Tukaram Best International Marathi Film Award) alongside a World Competition, Global Cinema, and Country Focus sections.",
  fee:"$25 USD for features (70+ min). Separate delegate registration fee: ₹800 (not a submission fee).",
  formats:"World Competition, Marathi Competition, Global Cinema, Country Focus, Retrospective",
  docs:"Censorship certificate/visa of the country of production; English subtitles mandatory for non-English entries.",
  platform:"FilmFreeway",
  url:"https://piffindia.com/" },

{ id:"habitat", cat:"indian", name:"Habitat Film Festival", loc:"Delhi (India Habitat Centre), India",
  dates:"18th ed. May 15–24, 2026 (concluded)",
  deadline:"—",
  deadlineISO:null, statusOverride:"curated",
  concept:"Programming is drawn from curated partner selections (Film Critics Guild's Critics' Choice picks, IDPA, PSBT documentaries) rather than an advertised open call. What's publicly documented is free audience registration to attend screenings, not a filmmaker submission process.",
  fee:"—", formats:"—",
  docs:"No confirmed public submission channel found — contact the India Habitat Centre / IHC Film Club directly to inquire.",
  platform:"—",
  url:"https://indiahabitat.org/hff2026/" },

{ id:"msiff", cat:"indian", name:"Mumbai Shorts International Film Festival (MSIFF)", loc:"Mumbai, India",
  dates:"15th ed. — regular entries notified Nov 15, 2026 · late entries Nov 20, 2026 · screenings/awards Dec 6, 2026",
  deadline:"Exact deadline not precisely surfaced — implied to fall before mid-November 2026",
  deadlineISO:null, statusOverride:"tba",
  concept:"The closest and most established match for 'Mumbai Short Film Festival' — run via Miniboxoffice.com. Several similarly-named smaller events exist (Mumbai Entertainment International Short Film Festival, Mumbai Short and Documentary Film Festival) — verify which one you actually mean.",
  fee:"Unconfirmed — appears to use a 'submit free for pre-selection, pay only if selected' model via bank transfer.",
  formats:"Shorts (runtime caps unconfirmed)",
  docs:"Standard online submission — details thin in public sources, verify directly.",
  platform:"FilmFreeway, Festhome, and own site (miniboxoffice.com)",
  url:"https://miniboxoffice.com/mumbai-shorts-international-film-festival" },

{ id:"spiff", cat:"indian", name:"Smita Patil International Film Festival (SPIFF)", loc:"Pune, India (at NFAI)",
  dates:"13th ed. confirmed for January 2027",
  deadline:"Not yet published for the 13th edition",
  deadlineISO:null, statusOverride:"tba",
  concept:"A short-film-focused festival (fiction, non-fiction, animation, under 40 min) honoring Smita Patil's legacy, founded 2012 by Arogya Sena, with a signature 'Best Female Filmmaker – Smita Patil Award of Recognition' category.",
  fee:"Free of cost",
  formats:"Best Short Fiction Film, Best Short International Film, Best Director, Best Female Filmmaker, Jury Special Mention",
  docs:"Online-only submission — no physical entries accepted.",
  platform:"FilmFreeway and Festhome",
  url:"https://spiffpune.com/",
  note:"Not to be confused with the unrelated Priyadarshni Academy 'Smita Patil Memorial Award' for Best Actress — a biennial acting-career award, not a submission-based festival." },

{ id:"filmbazaar", cat:"indian", name:"NFDC WAVES Film Bazaar", loc:"Goa, India (industry market, runs alongside IFFI)",
  dates:"20th ed. Nov 20–24, 2026",
  deadline:"2026 (Goa-edition) deadlines not yet published. The 2025-cycle pattern was Regular Sep 5 · Extended Sep 15 · Late Oct 6 — expect a similar Aug–Oct 2026 window.",
  deadlineISO:null, statusOverride:"tba",
  concept:"India's premier film industry market (not a public screening festival) — connects South Asian projects with financiers, sales agents, distributors, and festival programmers across several verticals: Viewing Room, Work-in-Progress Lab, Co-Production Market, Screenwriters' Lab, and Market Screenings.",
  fee:"Non-refundable INR fees apply per vertical; exact current schedule unconfirmed — check the annually-updated Rules &amp; Regulations PDF before relying on a figure.",
  formats:"Viewing Room (completed/post-production films), WIP Lab (selective, rough cuts), Co-Production Market, Screenwriters' Lab (Indian passport/OCI holders only), Market Screenings",
  docs:"Project brief, screener/rough cut (WIP Lab), synopsis, director bio, proof of production stage.",
  platform:"Own portal (filmbazaarindia.com / films.wavesbazaar.com) — not FilmFreeway",
  url:"https://filmbazaarindia.com/",
  note:"A separate spinoff, WAVES Doc Bazaar (documentary/animation only), runs in Mumbai alongside MIFF — its 2026 edition (Jun 16–18) has already concluded." },

// ---------------- AI-GENERATED FILM ----------------
{ id:"runwayaif", cat:"ai", name:"Runway AI Festival (AIF)", loc:"New York &amp; Los Angeles, USA (gala screenings)",
  dates:"4th annual ed. — galas Jun 11, 2026 (NYC) &amp; Jun 18, 2026 (LA)",
  deadline:"Window closed: Jan 28–Apr 27, 2026",
  deadlineISO:"2026-04-27",
  concept:"Broadened in 2026 beyond film into an interdisciplinary art-and-technology festival with multiple tracks. The Film track requires AI-generated video but is tool-agnostic — not Runway-exclusive.",
  fee:"Free",
  formats:"Film (3–15 min AI-generated video), Design, New Media, Fashion, Advertising, Gaming",
  docs:"Submission link plus a written description of the AI techniques used. Grand Prix $20,000 + 1M Runway credits; Gold $10,000 + 500K credits; Silver $5,000 + 500K credits.",
  platform:"Own portal (aif.runwayml.com)",
  url:"https://aif.runwayml.com/",
  note:"Next cycle expected ~January 2027." },

{ id:"astanaaaiff", cat:"ai", name:"Astana AI Film Festival (AAIFF)", loc:"Astana, Kazakhstan",
  dates:"Oct 1–3, 2026 (inaugural edition)",
  deadline:"Window: May 25–Aug 15, 2026",
  deadlineISO:"2026-08-15",
  concept:"The first major international festival dedicated purely to AI-generated short films, open worldwide regardless of studio access. Two tracks: Open Competition (any theme) and Thematic Competition (2026 theme: 'The Future Worth Living In').",
  fee:"Free",
  formats:"Shorts up to 10 minutes — 25 finalists total (10 Thematic, 15 Open)",
  docs:"No formal application portal — submit via a YouTube or cloud-storage link on the official site.",
  platform:"Own site (aaiff.ai) — not FilmFreeway",
  url:"https://www.aaiff.ai/",
  note:"Prize pool: $1,000,000 combined — the largest AI-film prize pool found in this research. Also see the disambiguation card below — 'AAIFF' is shared by three unrelated organizations." },

{ id:"austinai", cat:"ai", name:"Austin AI Film Festival (also branded 'AAIFF')", loc:"Austin, Texas, USA",
  dates:"2nd annual live edition — Oct 16–17, 2026",
  deadline:"Window: Apr 15–Aug 15, 2026",
  deadlineISO:"2026-08-15",
  concept:"Hosted via Curious Refuge. Celebrates narrative films made by humans using generative AI tools as a creative aid — 'the best and most original generative films.'",
  fee:"Paid tiers exist; exact amounts unconfirmed — check austinaifilmfest.com directly.",
  formats:"11 award categories including AI Feature Film, AI Short Film, AI Micro-Short Film, and Hybrid Film",
  docs:"Standard online submission — verify current requirements on the official site.",
  platform:"austinaifilmfest.com, also listed on FilmFreeway",
  url:"https://www.austinaifilmfest.com/" },

{ id:"aaiffnyc", cat:"ai", name:"Asian American International Film Festival — NOT an AI festival", loc:"New York City, USA", disambig:true,
  dates:"49th ed. Jul 30–Aug 9, 2026 (hybrid NYC/VOD)",
  deadline:"Was Mar 15, 2026 — closed",
  deadlineISO:"2026-03-15",
  concept:"Included here purely for disambiguation: this long-running festival (est. 1978, run by Asian CineVision) also uses the acronym 'AAIFF' but has nothing to do with AI-generated film. If you're looking for the AI festival, you likely mean Astana AAIFF or the Austin AI Film Festival above.",
  fee:"—", formats:"—", docs:"—", platform:"—",
  url:"https://www.aaiff.org/" },

{ id:"curiousrefuge", cat:"ai", name:"Curious Refuge — Feel Good AI Film Competition", loc:"Online (community competition)",
  dates:"Winners announced Apr 9, 2026",
  deadline:"Was Mar 10, 2026, 11:59pm PT — closed",
  deadlineISO:"2026-03-10",
  concept:"A themed AI-film competition run by the Curious Refuge community for warm, hopeful 'feel-good' AI-generated shorts. Curious Refuge itself is an AI-filmmaker community/platform, not a single festival — it also maintains a directory of 90+ AI film events.",
  fee:"Unconfirmed (likely free, community-run)",
  formats:"Short films, themed around hopeful/feel-good stories",
  docs:"Standard online submission via curiousrefuge.com.",
  platform:"curiousrefuge.com",
  url:"https://curiousrefuge.com/",
  note:"$10,000 cash pool (1st/2nd/3rd + audience-choice). Next round expected ~early 2027." },

{ id:"waiff", cat:"ai", name:"World AI Film Festival (WAIFF)", loc:"Cannes, France &amp; Los Angeles, USA",
  dates:"WAIFF Cannes: Apr 21–22, 2026 (concluded, ~5,500 submissions from 80+ countries) · WAIFF LA: Oct 10–11, 2026",
  deadline:"Cannes edition closed. LA-edition deadline unconfirmed — likely still open given the October event date.",
  deadlineISO:null, statusOverride:"tba",
  concept:"Run by Institut EuropIA. Unusually strict rules: every submission must use at least three different generative AI tools (including one for image generation) plus a required 'production file' explaining AI usage.",
  fee:"Unconfirmed",
  formats:"Best AI Short (5–10 min), Best AI Feature (25+ min), Best AI Micro-Series (vertical/social, 4–6 episodes ≤2 min each)",
  docs:"Submission via FilmFreeway + HUG.art per the official rules PDF; production file detailing AI tool usage required.",
  platform:"FilmFreeway + HUG.art",
  url:"https://worldaifilmfestival.com/",
  note:"Separately, the official Cannes Festival (79th ed.) banned generative-AI work from Palme d'Or/Official Competition in April 2026 but introduced a new 'Hybrid Cinema' recognition category for human+AI co-authored work — distinct from WAIFF, submission mechanics undetailed." },

{ id:"replyai", cat:"ai", name:"Reply AI Film Festival", loc:"Venice, Italy (finalist screening, tied to Venice Film Festival)",
  dates:"Finalist screening Sep 2–12, 2026, during the 83rd Venice Film Festival",
  deadline:"Was Jun 2, 2026, 23:59 CEST — closed (screening event still upcoming)",
  deadlineISO:"2026-06-02",
  concept:"Run by Reply (Italian tech/consulting company) with Mastercard, tied to Venice. Shorts using generative AI as a core production component, with a sub-category for films addressing 'humanity's biggest challenges' and a separate 'Reply AI Studios Grand Prix' for technical/workflow mastery.",
  fee:"Free",
  formats:"Short films — teams up to 8 members, entrants must be 18+",
  docs:"Required PDF detailing AI usage in the production workflow.",
  platform:"challenges.reply.com",
  url:"https://challenges.reply.com/challenges/creative/aifilmfestival/home/",
  note:"Top 10 finalists get travel/accommodation to a Venice premiere event." },

{ id:"lifeart", cat:"ai", name:"LifeArt AI Global Film Festival", loc:"Online / Festhome-hosted",
  dates:"2026 event dates unconfirmed",
  deadline:"Regular May 1, 2026 · Late Jun 2, 2026 — both closed",
  deadlineISO:"2026-06-02",
  concept:"Billed as an IMDb-qualifying festival dedicated exclusively to AI-generated film, animation, digital art, and experimental AI media.",
  fee:"Paid via credit card; multiple entries/categories allowed; exact amounts unconfirmed; non-refundable.",
  formats:"8 official categories including AI-Generated Films &amp; Animation (Short/Feature), AI Commercial &amp; Advertising, AI Music Video",
  docs:"Non-English submissions require English subtitles; online link + password entered in the submission form.",
  platform:"Festhome (exclusive)",
  url:"https://www.lifeartfestival.com/ai" },

{ id:"aiffi", cat:"ai", name:"AIFFI — International Festival for AI-Generated Short Films", loc:"Roatán, Honduras",
  dates:"Apr 17–18, 2026 (inaugural edition, already occurred)",
  deadline:"Was Mar 31, 2026 — closed",
  deadlineISO:"2026-03-31",
  concept:"A hybrid physical + global digital screening festival, exclusively for AI-generated shorts — the first Central America festival dedicated to AI cinema.",
  fee:"Unconfirmed",
  formats:"Short films, AI-generated",
  docs:"Standard submission — verify current requirements directly.",
  platform:"FilmFreeway (filmfreeway.com/aiffi) and official site aiffi.org",
  url:"https://filmfreeway.com/aiffi",
  note:"$10,000+ prize pool across categories. Distinct from the similarly-named 'AI International Film Festival' (aifilmfest.org) below — don't conflate them." },

{ id:"aifilmfestorg", cat:"ai", name:"AI International Film Festival", loc:"Hollywood, California, USA",
  dates:"Aug 15, 2026",
  deadline:"Was Feb 21, 2026 — closed (event still upcoming)",
  deadlineISO:"2026-02-21",
  concept:"Self-described as the 'world's first AI film festival' (founded 2021) — an interactive format with filmmaker discussions and an AI Expert Panel, not just screenings.",
  fee:"Varies by category, exact amounts unconfirmed",
  formats:"Multiple categories — most entrants submit to 2–4",
  docs:"Standard submission via the official site.",
  platform:"aifilmfest.org",
  url:"https://aifilmfest.org/",
  note:"Listed prize: $0 cash — appears prestige/exposure-based rather than cash-prize driven." },

{ id:"aiforgood", cat:"ai", name:"AI for Good Film Festival", loc:"Geneva, Switzerland (ITU / UN agency)",
  dates:"Screened during the AI for Good Global Summit, Jul 7–10, 2026 (concluded)",
  deadline:"Was May 15, 2026, 23:59 CEST — closed",
  deadlineISO:"2026-05-15",
  concept:"Run by the UN's International Telecommunication Union. AI must be a 'core component' but films need not be fully AI-generated — broader than most AI-only festivals, tied to the UN's AI-for-social-good mission.",
  fee:"Unconfirmed — likely free, as a UN-agency-run event",
  formats:"Films addressing AI for social good themes",
  docs:"Standard submission via the official summit portal.",
  platform:"aiforgood.itu.int",
  url:"https://aiforgood.itu.int/ai-for-good-film-festival/",
  note:"Next edition presumably ties to the 2027 Summit — not yet published." },

{ id:"wearehuman", cat:"ai", name:"We Are Human Festival", loc:"Paris, France",
  dates:"Awards ceremony Nov 24, 2026, Forum des Images (inaugural edition)",
  deadline:"Window: Jun 1–Sep 30, 2026",
  deadlineISO:"2026-09-30",
  concept:"Not a generic 'AI film' festival — specifically explores AI and human-rights themes, built around Article 1 of the Universal Declaration of Human Rights. Accepts human/AI hybrid works, 1–10 minutes.",
  fee:"Free",
  formats:"Human/AI hybrid short works, 1–10 minutes — 20 projects selected for international touring screenings",
  docs:"Standard online submission via the official call for films.",
  platform:"wearehuman.foundation",
  url:"https://wearehuman.foundation/en/call-for-films/" },

{ id:"bjiff", cat:"ai", name:"Beijing International Film Festival — AIGC Film Section", loc:"Beijing, China",
  dates:"16th BJIFF",
  deadline:"Was Mar 30, 2026 — closed (works completed Jan 2025–Mar 2026 eligible)",
  deadlineISO:"2026-03-30",
  concept:"'AIGC' (AI-Generated Content) is China's official industry term. Three tracks — Feature Film Group, Short Film Group, AI Series Group. Notable as a government/state-affiliated major festival institutionalizing AI categories into its mainstream programme.",
  fee:"Unconfirmed (limited English-language sources)",
  formats:"Feature, Short, AI Series",
  docs:"Details limited in English-language sources — verify directly with BJIFF.",
  platform:"bjiff.com",
  url:"https://www.bjiff.com/" },

{ id:"neuwave", cat:"ai", name:"Neu Wave AI Film Festival", loc:"Los Angeles, USA",
  dates:"3rd annual edition, Oct 14–15, 2026",
  deadline:"Aug 31, 2026",
  deadlineISO:"2026-08-31",
  concept:"An AI film festival and community event based in Los Angeles — lower research confidence than the entries above; verify current details directly.",
  fee:"Unconfirmed",
  formats:"Not fully detailed in public sources",
  docs:"Verify directly on neuwavefest.com.",
  platform:"neuwavefest.com",
  url:"https://neuwavefest.com/" },

{ id:"biaiff", cat:"ai", name:"Bochnia International AI Film Festival (BIAIFF)", loc:"Bochnia, Poland",
  dates:"Ceremony Sep 17, 2026",
  deadline:"Aug 15, 2026",
  deadlineISO:"2026-08-15",
  concept:"A Poland-based AI film festival with a modest, clearly stated prize pool.",
  fee:"Unconfirmed",
  formats:"Not fully detailed in public sources",
  docs:"Verify directly on biaiff.pl.",
  platform:"biaiff.pl",
  url:"https://www.biaiff.pl/",
  note:"Prize pool $2,500 (Grand Prix $1,200)." },

{ id:"lundinstudio", cat:"ai", name:"LundinStudio AI Film Festival", loc:"Unconfirmed",
  dates:"Event Mar 18–19, 2027",
  deadline:"Unusually long window: Apr 16, 2026–Jan 21, 2027",
  deadlineISO:"2027-01-21",
  concept:"Lowest research confidence of the AI festivals tracked here — details are thin; treat as speculative until closer to the date.",
  fee:"Unconfirmed", formats:"Unconfirmed",
  docs:"Verify directly before relying on this listing.",
  platform:"Unconfirmed",
  url:"" },

{ id:"ltxshortest", cat:"ai", name:"AI Shortest Film Competition (by LTX / Forward Festival)", loc:"Berlin, Germany",
  dates:"Screening at the Shortest AI Film Festival, Berlin, Aug 27–28, 2026",
  deadline:"Was Jul 5, 2026 — closed",
  deadlineISO:"2026-07-05",
  concept:"Notably tool-locked, unlike most other AI festivals: films must be ≤60 seconds and made specifically with LTX, delivered as .mp4.",
  fee:"Unconfirmed",
  formats:"≤60-second films, LTX tool required",
  docs:".mp4 format required; verify current specs on forward-festival.com.",
  platform:"forward-festival.com",
  url:"https://www.forward-festival.com/page/ai-shortest-film-competition-by-ltx" },

{ id:"futurefilmfest", cat:"ai", name:"Future Film Fest (3F) — Narrative &amp; AI Shorts / AI Shorts Open Category", loc:"Unconfirmed",
  dates:"Unconfirmed",
  deadline:"Unconfirmed",
  deadlineISO:null, statusOverride:"tba",
  concept:"Runs both a general Narrative &amp; AI Shorts competition ($58,000 pool) and a separate AI Shorts Open Category specifically for under-30 creators ($8,000 pool).",
  fee:"Unconfirmed", formats:"Narrative &amp; AI Shorts, AI Shorts Open (under-30)",
  docs:"Verify directly — dates and requirements not confirmed in public sources.",
  platform:"Unconfirmed",
  url:"" },
];
